language: go
go:
  - "1.13"
  - "1.14"
install:
  - sudo apt-get install libasound2-dev
  - go install -v ./...
  - go test -race -coverprofile=coverage.txt -covermode=atomic ./...
after_success:
  - bash <(curl -s https://codecov.io/bash)
